# Generated by Django 2.2.3 on 2019-09-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20190924_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title_gp',
            new_name='title_jp',
        ),
    ]
