# Generated by Django 2.2.3 on 2019-09-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='previous_evolution',
            new_name='next_evolution',
        ),
    ]
