# Generated by Django 2.2.3 on 2019-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20190928_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(default=None, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='lon',
            field=models.FloatField(default=None, verbose_name='долгота'),
            preserve_default=False,
        ),
    ]
